# Generated by Django 4.2.4 on 2023-08-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_shopadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(help_text='user', max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.IntegerField(max_length=15)),
                ('Location', models.TextField(help_text='location')),
            ],
        ),
    ]
