# Generated by Django 4.2.4 on 2023-08-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_registration_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='PhoneNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
