# Generated by Django 4.2.4 on 2023-08-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_loginmodel_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginmodel',
            new_name='login',
        ),
    ]
