# Generated by Django 4.2.4 on 2023-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_authenticate_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
