# Generated by Django 4.2.4 on 2023-09-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_authenticate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticate',
            name='Password1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
