# Generated by Django 3.2.12 on 2023-07-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='TAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='TEmail',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
