# Generated by Django 4.2.4 on 2023-08-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=33)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
