# Generated by Django 3.2.12 on 2023-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=33)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.TextField(max_length=55)),
                ('message', models.TextField(max_length=100)),
            ],
        ),
    ]
