# Generated by Django 3.2.12 on 2023-08-04 16:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='login',
            managers=[
                ('empAuth_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='message',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='subject',
            field=models.TextField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
