# Generated by Django 3.2.12 on 2023-08-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0002_auto_20230804_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='subject',
            field=models.TextField(max_length=55),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
