# Generated by Django 3.2.12 on 2023-08-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0003_auto_20230804_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
