# Generated by Django 3.2.12 on 2023-08-05 06:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0004_alter_login_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='login',
            managers=[
                ('create_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
