# Generated by Django 4.2.4 on 2023-08-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0005_alter_login_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='login',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.EmailField(max_length=50),
        ),
    ]
