# Generated by Django 4.2.4 on 2023-08-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0007_remove_login_password_login_email_login_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
