# Generated by Django 4.2.4 on 2023-08-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0009_alter_login_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(default='phone number', max_length=15),
        ),
    ]
