# Generated by Django 4.2.4 on 2023-08-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0010_alter_login_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=33),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=55),
        ),
    ]
