# Generated by Django 3.2.12 on 2023-08-05 09:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('psw', models.EmailField(max_length=50)),
                ('remember', models.EmailField(max_length=35)),
            ],
            managers=[
                ('create_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
