# Generated by Django 4.2.4 on 2023-08-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='login',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='remember',
            field=models.TextField(max_length=35),
        ),
    ]
